[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ooi-hyd-tools"
version = "0.4.0"
description = "Tools and scripts for working with OOI hydrophone data"
requires-python = ">=3.9"
dependencies = [
    "fsspec",
    "s3fs",
    "numpy",
    "soundfile",
    "tqdm",
    "requests",
    "aiohttp",
    "jupyter",
    "obspy",
    "loguru",
    "click",
    "matplotlib",
    "pydantic>2",
    "prefect>=2,<3",
    #"mbari-pbp @ git+ssh://git@github.com/jdduprey/pbp.git@ooi-qaqc",
    "mbari-pbp",
]

[project.scripts]
acoustic-pipeline = "ooi_hyd_tools.pipeline:run_acoustic_pipeline"

[tool.hatch.build.targets.wheel]
packages = ["ooi_hyd_tools"]

[tool.hatch.metadata]
allow-direct-references = true